package com.vegayan.airtelmanagement.audit.dto;

/**
 * One audit record on its way to {@code sp_insert_ui_actions_log} - the six
 * procedure parameters and nothing else.
 *
 * <p>Immutable and self-contained on purpose: the write happens on a pool
 * thread after the request has returned, where neither the SecurityContext nor
 * the HTTP request is still available. Everything the write needs (the actor
 * above all) is resolved on the request thread and captured here.
 *
 * <p>{@code createdAt} is absent by design. The timestamp is generated by
 * MySQL from {@code UI_ACTIONS_LOGGER.created_at DEFAULT CURRENT_TIMESTAMP(6)},
 * so neither the application nor the browser can influence when an action is
 * recorded as having happened.
 */
public record AuditLogEntry(
        String module,
        String subModule,
        String action,
        Long   actorUserId,
        Long   affectedUserId,
        String remark
) {

    /** Longest value {@code UI_ACTIONS_LOGGER.remark} accepts. */
    public static final int REMARK_MAX_LENGTH = 1000;

    /** Longest value the module / sub_module / action columns accept. */
    public static final int LABEL_MAX_LENGTH = 100;

    /**
     * Trims every field to what the column can physically hold, so a long
     * free-text remark can never turn a business success into a failed audit
     * write (and, with strict SQL mode on, a truncation error).
     */
    public AuditLogEntry {
        module    = clip(module,    LABEL_MAX_LENGTH);
        subModule = clip(subModule, LABEL_MAX_LENGTH);
        action    = clip(action,    LABEL_MAX_LENGTH);
        remark    = clip(remark,    REMARK_MAX_LENGTH);
    }

    private static String clip(String value, int max) {
        if (value == null) {
            return null;
        }
        String trimmed = value.trim();
        if (trimmed.isEmpty()) {
            return null;
        }
        return trimmed.length() <= max ? trimmed : trimmed.substring(0, max);
    }

    /**
     * Key used to collapse a double-submitted action into one row - see
     * {@code AuditLogService}. Deliberately excludes any timestamp: two
     * identical entries seconds apart are the thing being detected.
     */
    public String dedupeKey() {
        return actorUserId + "|" + module + "|" + subModule + "|" + action
                + "|" + affectedUserId + "|" + remark;
    }
}
