package com.vegayan.airtelmanagement.schedular.dto;

import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * One finding raised against a MOP version, as stored in {@code mop_finding}.
 *
 * <p>{@code findingRef} ("F-01") is generated by {@code sp_mop_finding_add} and
 * is unique per version, not globally - it is what the reviewer sees, while
 * {@code findingId} is what the state endpoints address.
 */
@Getter
@Setter
public class MopFindingDto {

    private Long findingId;

    /** Per-version reference the procedure builds - "F-01", "F-02". */
    private String findingRef;

    private Long versionId;

    /** Page of the MOP document the finding was raised against. */
    private Integer pageNo;

    /**
     * Free-text step reference. The design's per-step flagging fills this; a
     * finding raised from the page toolbar leaves it null.
     */
    private String stepRef;

    private String description;

    /** open / resolved / withdrawn. Only 'open' blocks validation. */
    private String state;

    /** OLM id - `app_user` is empty, so no name can be resolved. */
    private String raisedBy;

    private LocalDateTime raisedAt;

    private LocalDateTime resolvedAt;
}
